// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: email_verification_codes.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createEmailVerificationCode = `-- name: CreateEmailVerificationCode :one
INSERT INTO email_verification_codes (
    email,
    code,
    expires_at,
    created_at
)
VALUES ($1, $2, $3, now())
RETURNING id, email, code, expires_at, used_at, created_at
`

type CreateEmailVerificationCodeParams struct {
	Email     string
	Code      string
	ExpiresAt pgtype.Timestamptz
}

func (q *Queries) CreateEmailVerificationCode(ctx context.Context, arg CreateEmailVerificationCodeParams) (EmailVerificationCode, error) {
	row := q.db.QueryRow(ctx, createEmailVerificationCode, arg.Email, arg.Code, arg.ExpiresAt)
	var i EmailVerificationCode
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Code,
		&i.ExpiresAt,
		&i.UsedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getEmailVerificationCode = `-- name: GetEmailVerificationCode :one
SELECT id, email, code, expires_at, used_at, created_at
FROM email_verification_codes
WHERE email = $1
  AND code = $2
  AND expires_at > $3
  AND used_at IS NULL
ORDER BY created_at DESC
LIMIT 1
`

type GetEmailVerificationCodeParams struct {
	Email     string
	Code      string
	ExpiresAt pgtype.Timestamptz
}

func (q *Queries) GetEmailVerificationCode(ctx context.Context, arg GetEmailVerificationCodeParams) (EmailVerificationCode, error) {
	row := q.db.QueryRow(ctx, getEmailVerificationCode, arg.Email, arg.Code, arg.ExpiresAt)
	var i EmailVerificationCode
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Code,
		&i.ExpiresAt,
		&i.UsedAt,
		&i.CreatedAt,
	)
	return i, err
}

const markEmailVerificationCodeUsed = `-- name: MarkEmailVerificationCodeUsed :exec
UPDATE email_verification_codes
SET used_at = $2
WHERE id = $1
`

type MarkEmailVerificationCodeUsedParams struct {
	ID     pgtype.UUID
	UsedAt pgtype.Timestamptz
}

func (q *Queries) MarkEmailVerificationCodeUsed(ctx context.Context, arg MarkEmailVerificationCodeUsedParams) error {
	_, err := q.db.Exec(ctx, markEmailVerificationCodeUsed, arg.ID, arg.UsedAt)
	return err
}
