// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type EmailVerificationCode struct {
	ID        pgtype.UUID
	Email     string
	Code      string
	ExpiresAt pgtype.Timestamptz
	UsedAt    pgtype.Timestamptz
	CreatedAt pgtype.Timestamptz
}

type InviteCode struct {
	ID              pgtype.UUID
	TeamID          pgtype.UUID
	Email           string
	Code            string
	ExpiresAt       pgtype.Timestamptz
	RedeemedAt      pgtype.Timestamptz
	CreatedByUserID pgtype.UUID
	CreatedAt       pgtype.Timestamptz
}

type Team struct {
	ID        pgtype.UUID
	Domain    string
	Name      string
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

type TeamMembership struct {
	ID        pgtype.UUID
	TeamID    pgtype.UUID
	UserID    pgtype.UUID
	Role      string
	JoinedAt  pgtype.Timestamptz
	CreatedAt pgtype.Timestamptz
}

type TimezoneState struct {
	UserID           pgtype.UUID
	Timezone         string
	UtcOffsetMinutes int32
	CountryCode      string
	ReportedAt       pgtype.Timestamptz
	UpdatedAt        pgtype.Timestamptz
}

type TimezoneVisibility struct {
	UserID             pgtype.UUID
	HiddenUntil        pgtype.Timestamptz
	HiddenIndefinitely bool
	LastReminderAt     pgtype.Timestamptz
	UpdatedAt          pgtype.Timestamptz
}

type User struct {
	ID              pgtype.UUID
	Email           string
	EmailDomain     string
	EmailVerifiedAt pgtype.Timestamptz
	CreatedAt       pgtype.Timestamptz
	UpdatedAt       pgtype.Timestamptz
}

type WorkingHour struct {
	UserID          pgtype.UUID
	StartMinute     int32
	EndMinute       int32
	SaturdayEnabled bool
	SundayEnabled   bool
	CreatedAt       pgtype.Timestamptz
	UpdatedAt       pgtype.Timestamptz
}
