// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: team_memberships.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createTeamMembership = `-- name: CreateTeamMembership :exec
INSERT INTO team_memberships (
    team_id,
    user_id,
    role,
    joined_at,
    created_at
)
VALUES ($1, $2, $3, $4, now())
ON CONFLICT (team_id, user_id) DO NOTHING
`

type CreateTeamMembershipParams struct {
	TeamID   pgtype.UUID
	UserID   pgtype.UUID
	Role     string
	JoinedAt pgtype.Timestamptz
}

func (q *Queries) CreateTeamMembership(ctx context.Context, arg CreateTeamMembershipParams) error {
	_, err := q.db.Exec(ctx, createTeamMembership,
		arg.TeamID,
		arg.UserID,
		arg.Role,
		arg.JoinedAt,
	)
	return err
}

const getTeamMembership = `-- name: GetTeamMembership :one
SELECT id, team_id, user_id, role, joined_at, created_at
FROM team_memberships
WHERE team_id = $1
  AND user_id = $2
`

type GetTeamMembershipParams struct {
	TeamID pgtype.UUID
	UserID pgtype.UUID
}

func (q *Queries) GetTeamMembership(ctx context.Context, arg GetTeamMembershipParams) (TeamMembership, error) {
	row := q.db.QueryRow(ctx, getTeamMembership, arg.TeamID, arg.UserID)
	var i TeamMembership
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.UserID,
		&i.Role,
		&i.JoinedAt,
		&i.CreatedAt,
	)
	return i, err
}
