// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: teams.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countTeamMembers = `-- name: CountTeamMembers :one
SELECT COUNT(*)
FROM team_memberships
WHERE team_id = $1
`

func (q *Queries) CountTeamMembers(ctx context.Context, teamID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countTeamMembers, teamID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createTeam = `-- name: CreateTeam :one
INSERT INTO teams (
    domain,
    name,
    created_at,
    updated_at
)
VALUES ($1, $2, now(), now())
RETURNING id, domain, name, created_at, updated_at
`

type CreateTeamParams struct {
	Domain string
	Name   string
}

func (q *Queries) CreateTeam(ctx context.Context, arg CreateTeamParams) (Team, error) {
	row := q.db.QueryRow(ctx, createTeam, arg.Domain, arg.Name)
	var i Team
	err := row.Scan(
		&i.ID,
		&i.Domain,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTeamByDomain = `-- name: GetTeamByDomain :one
SELECT id, domain, name, created_at, updated_at
FROM teams
WHERE domain = $1
`

func (q *Queries) GetTeamByDomain(ctx context.Context, domain string) (Team, error) {
	row := q.db.QueryRow(ctx, getTeamByDomain, domain)
	var i Team
	err := row.Scan(
		&i.ID,
		&i.Domain,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
