// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (
    email,
    email_domain,
    email_verified_at,
    created_at,
    updated_at
)
VALUES ($1, $2, $3, now(), now())
RETURNING id, email, email_domain, email_verified_at, created_at, updated_at
`

type CreateUserParams struct {
	Email           string
	EmailDomain     string
	EmailVerifiedAt pgtype.Timestamptz
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser, arg.Email, arg.EmailDomain, arg.EmailVerifiedAt)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.EmailDomain,
		&i.EmailVerifiedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, email, email_domain, email_verified_at, created_at, updated_at
FROM users
WHERE email = $1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.EmailDomain,
		&i.EmailVerifiedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, email, email_domain, email_verified_at, created_at, updated_at
FROM users
WHERE id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, id pgtype.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.EmailDomain,
		&i.EmailVerifiedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateUserVerifiedAt = `-- name: UpdateUserVerifiedAt :one
UPDATE users
SET email_verified_at = $2,
    updated_at = now()
WHERE id = $1
RETURNING id, email, email_domain, email_verified_at, created_at, updated_at
`

type UpdateUserVerifiedAtParams struct {
	ID              pgtype.UUID
	EmailVerifiedAt pgtype.Timestamptz
}

func (q *Queries) UpdateUserVerifiedAt(ctx context.Context, arg UpdateUserVerifiedAtParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUserVerifiedAt, arg.ID, arg.EmailVerifiedAt)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.EmailDomain,
		&i.EmailVerifiedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
